###############  spring配置 ###############
spring:
  # jpa配置
  jpa:
    # 非初始化库请注释
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    # 非初始化库请注释
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # 数据源配置 (mysql/oracle)
  datasource:
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      maximum-pool-size: 50
      max-lifetime: 1200000
      validation-timeout: 5000
      idle-timeout: 600000
      username: root
      password: 1119102
      jdbc-url: jdbc:mysql://10.0.14.102:3306/any_test_20191119?useSSL=false&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver

###############  swagger配置 ###############
swagger:
  enable: true

###############  anyMarket配置 ###############
jrx:
  market:
    file-path: data/file/

###############  any Client配置 ###############
anyest:
  admin:
    # 报表配置
    invoke-type: REMOTE
    strategy-report-es-sql: false
    view-data-type: DETAIL
  client:
    # 是否开启feign客户端
    enable: true
    # 是否使用clientApi
    able-api: true
    # 请求超时
    ReadTimeout: 500000
    # 连接超时
    ConnectTimeout: 50000

###############  权限配置 ###############
# 综管配置
auth:
  setting:
    # token超时时间 单位：分钟
    tokenExpTimeMinute: 60

# 拦截器配置
filter:
  setting:
    # 设置默认人员,格式：userName-userId-nikeName
    user: developer-242-开发人员
    # 设置默认机构(可设置多个),格式：projectName-projectId,projectName2-projectId2
    project: 测试机构-220314,测试机构2-243
    # 鉴权模式: AUTH(开启权限),LOGIN(仅登录),NOT(无鉴权)
    authModel: LOGIN
    # 本地ip:port（真实ip,综管中心要重定向回来）
    localUrl: 10.0.14.102:${server.port}

###############  eureka配置 ###############
eureka:
  instance:
    ip-address: 10.0.14.102
    instance-id: ${eureka.instance.ip-address}:${server.port}

  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://${eureka.instance.instance-id}}/eureka/

logging:
  level:
    jrx.anyest.base: debug
